title: Enze "Alex" Liu
subtitle: Computer Security and Privacy Researcher
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "https://alexliu0809.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /#/
    - text: Publications
      url: /publications/
    - text: Recent News
      url: /news/
    #- text: Research
      #url: /research/
    - text: Blog
      url: /blog/
#    - text: Shop
#      url : /shop/
#    - text: Contact Me
#      url : /contact/
#    - text: Styleguide
#      url: /styleguide/

recent_news:
  - date: 2019-09-23
    content: Joining UCSD as a first-year PhD student! I am affiliated with Sysnet and CryptoSec research groups.
  - date: 2019-09-08
    content: Arrived in San Diego! Love the sunshine here.
  - date: 2019-05-20
    content: Presenting our paper "Reasoning Analytically About Password-Cracking Software" at IEEE S&P 2019 (Oakland).
  - date: 2019-02-01
    content: After two years of work, our work on reasoning analytically about password-cracking software is finally accepted by IEEE S&P 2019 ("Oakland").
  - date: 2018-03-21
    content: Received my master's degree from UChicago! Many thanks to my family and friends who have always been supportive.
  - date: 2016-09-20
    content: Starting my master's study at The University of Chicago.

# Edit these details 

author_logo: profile.png
author: Enze "Alex" Liu
author_bio: Hi, my name is Enze (pronounced like the italian name Enzo) Liu. You can also call me "Alex". Right now I am a first-year PhD student in Computer Science at UC San Diego advised by Stefan Savage and Geoffrey Voelker. I am broadly interested in computer security and privacy. My current research focuses on improving cybersecurity with large-scale empirical analyses. Previously, I did some research on passwords with Blase Ur and David Cash at the University of Chicago.
author_email: "e7liu@eng.ucsd.edu"
author_location: La Jolla, CA
author_website_url: "https://alexliu0809.github.io"

author_work_experiences: 
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: true

author_education_details:
              - college_logo: ucsd.png
                college_name: University of California San Diego
                college_url: http://www.ucsd.edu
                college_degree: PhD in Computer Science
                description: 2019.06 - Present
                visibility: true
              - college_logo: uchicago.png
                college_name: The University of Chicago
                college_url: http://www.uchicago.edu
                college_degree: MS in Computer Science
                description: 2016.09 - 2018.03
                visibility: true
              - college_logo: ucl.png
                college_name: University College London
                college_url: http://www.ucl.ac.uk
                college_degree: Study Abroad
                description: 2015.09 - 2016.06
                visibility: true
              - college_logo: bit.png
                college_name: Beijing Institute of Technology
                college_url: http://www.bit.edu.cn
                college_degree: BS in Software Engineering
                description: 2012.09 - 2016.06
                visibility: true

author_projects_details:
              - project_thumbnail: hc.jpeg
                project_title: Reasoning Analytically About Password-Cracking Software
                project_description: A software to reason analytically and efficiently about transformation-based password cracking in software tools like John the Ripper (JtR) and Hashcat (HC).
                project_url: https://github.com/UChicagoSUPERgroup/analytic-password-cracking
                visibility: true

              # - project_thumbnail: programmingebooks.png
              #   project_title: Programming Ebooks
              #   project_description: A Platform to easily find and read programming books
              #   project_url: https://programmingebooks.com
              #   visibility: false

author_pubs_details:
              - title: Reasoning Analytically About Password-Cracking Software
                author_list: Enze Liu, Amanda Nakanishi, Maximilian Golla, David Cash, Blase Ur
                venue: The 40th IEEE Symposium on Security and Privacy (S&P)
                venue_short: IEEE S&P
                year: 2019
                links:
                  - type: PDF
                    url: https://www.blaseur.com/papers/sp19-pwcracking.pdf
                  - type: Code
                    url: https://github.com/UChicagoSUPERgroup/analytic-password-cracking/
                  - type: Slides
                    url: https://www.ieee-security.org/TC/SP2019/SP19-Slides-pdfs/Enze_Alex_Liu_-_06-Reasoning_Analytically_About_Password-Cracking_Software.pdf
                  - type: Video
                    url: https://youtu.be/kSfmTV0GTIM




# social links
github_username:  alexliu0809
linkedin_username: alex-enze-liu-809859125
twitter_username: alexliu1
#facebook_username: johndoe
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments using disqus
#disqus_shortname: sujay-kundu  

# wakatime username (coding activity)
wakatime_username: alexliu0809

# formspree (contact form)
formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_projects_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/